name: sandbox-helloworld-haskell
version: 0.1.0

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sandbox-helloworld-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sandbox-helloworld-haskell
